<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="LHTU05CG4472DYW" name="com.cet.phd.PhdUserAdminAddNewUser_Test" tests="19" failures="2" timestamp="2020-12-18T16:16:49 IST" time="68.950" errors="0">
  <testcase name="addNewUserValidate_Test" time="10.687" classname="com.cet.phd.PhdUserAdminAddNewUser_Test"/>
  <testcase name="addNewUserFirstNameDisabled_Test" time="3.652" classname="com.cet.phd.PhdUserAdminAddNewUser_Test"/>
  <testcase name="addNewUserFirstNameDB_Test" time="2.087" classname="com.cet.phd.PhdUserAdminAddNewUser_Test"/>
  <testcase name="addNewUserLastNameDisabled_Test" time="1.503" classname="com.cet.phd.PhdUserAdminAddNewUser_Test"/>
  <testcase name="addNewUserLastNameDB_Test" time="2.046" classname="com.cet.phd.PhdUserAdminAddNewUser_Test"/>
  <testcase name="addNewUserEmployeeIDDisabled_Test" time="15.621" classname="com.cet.phd.PhdUserAdminAddNewUser_Test"/>
  <testcase name="addNewUserEmployeeIDDB_Test" time="1.894" classname="com.cet.phd.PhdUserAdminAddNewUser_Test"/>
  <testcase name="addNewUserEmailIDDB_Test" time="1.948" classname="com.cet.phd.PhdUserAdminAddNewUser_Test">
    <failure type="java.lang.AssertionError" message="Failed:EmailID DB Value mismatched - Add User expected [] but found [kishork@optum.com]">
      <![CDATA[java.lang.AssertionError: Failed:EmailID DB Value mismatched - Add User expected [] but found [kishork@optum.com]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.cet.phd.PhdUserAdminAddNewUser_Test.addNewUserEmailIDDB_Test(PhdUserAdminAddNewUser_Test.java:105)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- addNewUserEmailIDDB_Test -->
  <testcase name="addNewUserEmailIDDisabled_Test" time="1.224" classname="com.cet.phd.PhdUserAdminAddNewUser_Test"/>
  <testcase name="addNewUserSupervisorDisabled_Test" time="1.276" classname="com.cet.phd.PhdUserAdminAddNewUser_Test"/>
  <testcase name="addNewUserSupervisorDB_Test" time="1.691" classname="com.cet.phd.PhdUserAdminAddNewUser_Test"/>
  <testcase name="addNewUserManagerDisabled_Test" time="1.265" classname="com.cet.phd.PhdUserAdminAddNewUser_Test"/>
  <testcase name="assignWorkStatus_Test" time="2.586" classname="com.cet.phd.PhdUserAdminAddNewUser_Test"/>
  <testcase name="addNewUserManagerDB_Test" time="1.765" classname="com.cet.phd.PhdUserAdminAddNewUser_Test">
    <failure type="java.lang.AssertionError" message="Failed:Manager DB Value mismatched - Add User expected [ ] but found [Wajhi Ahmed]">
      <![CDATA[java.lang.AssertionError: Failed:Manager DB Value mismatched - Add User expected [ ] but found [Wajhi Ahmed]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.cet.phd.PhdUserAdminAddNewUser_Test.addNewUserManagerDB_Test(PhdUserAdminAddNewUser_Test.java:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- addNewUserManagerDB_Test -->
  <testcase name="activeStatus_Test" time="7.954" classname="com.cet.phd.PhdUserAdminAddNewUser_Test"/>
  <testcase name="inActiveStatus_Test" time="2.174" classname="com.cet.phd.PhdUserAdminAddNewUser_Test"/>
  <testcase name="selectTeamPHD_Test" time="3.238" classname="com.cet.phd.PhdUserAdminAddNewUser_Test"/>
  <testcase name="selectLanguagePHD_Test" time="6.339" classname="com.cet.phd.PhdUserAdminAddNewUser_Test"/>
  <testcase name="saveAddNewUser_Test" classname="com.cet.phd.PhdUserAdminAddNewUser_Test">
    <skipped/>
  </testcase> <!-- saveAddNewUser_Test -->
</testsuite> <!-- com.cet.phd.PhdUserAdminAddNewUser_Test -->
